### ISSUE TITLE
intl NumberFormatter

### ISSUE THREAD

**Issue by bojanz** [symfony/polyfill#10]
This package could polyfill the NumberFormatter. This is something symfony/intl never tried to do, but what we've mostly accomplished in [commerceguys/intl](https://github.com/commerceguys/intl/blob/master/src/Formatter/NumberFormatter.php).
We don't try to replicate the rounding behavior, but that could be done, at least partially.

Happy to discuss it via other channels as well.

**Comment by nicolas-grekas** [comment]
symfony/intl does have a NumberFormatter implementation. I didn't check, but is  commerceguys' better?
As far as I read correctly, both symfony/intl and commerceguys/intl provide polyfilling *and* add feature on top. It would be great to have the pure polyfill part of each here. Would someone like to give it a try?

**Comment by bojanz** [comment]
No, the symfony/intl one doesn't do any actual formatting.
The commerceguys one uses the CLDR/ICU number formats the do the same formatting the intl extension does.

**Comment by nicolas-grekas** [comment]
Then it could be interesting to have `ext-intl ∩ (commerceguys/intl ∪ symfony/intl)` here if someone wants to work on it!

**Comment by bojanz** [comment]
Merging the two NumberFormatters (to get the API and the logic) is a small task.

The bigger one is figuring out what to do with the data storage, since this repo would need to ship with the CLDR / ICU currency and number format data. That was previously symfony/intl territory*, so it needs discussion.

*symfony/intl ships with the currency data, but not with the number format data. There's an open issue about that.

**Comment by nicolas-grekas** [comment]
it is possible to get access to the data by using ext-intl only? if yes, we could move it here and make symfony/intl free from them (and rely only on the ext-intl interfaces, polyfilled or not)

**Comment by bojanz** [comment]
No, it's not. Both commerceguys/intl and symfony/intl have scripts that parse the data (downloaded from CLDR or ICU) and output JSON definitions.

**Comment by nicolas-grekas** [comment]
@bojanz would you like to submit a PR here adding NumberFormatter?

**Comment by bojanz** [comment]
I won't have time for that in the foreseeable future, sorry.

**Comment by nicolas-grekas** [comment]
How, no pb. Closing then.
