### ISSUE TITLE
Throwable interface in polyfill-php70

### ISSUE THREAD

**Issue by hlecorche** [symfony/polyfill#101]
Hello,

There is the `Error` class in polyfill-php70. But why isn't there any `Throwable` interface ?

http://php.net/manual/fr/language.errors.php7.php

Thanks

**Comment by keradus** [comment]
as you cannot mock behaviour of `Throwable`.
even if you would create interface, this:
`new Exception() instanceof Throwable` will not work

for that, if you cannot implement the behaviour, adding implement would be wrong

**Comment by nicolas-grekas** [comment]
Closing as explained.
