### ISSUE TITLE
Lint check: Fatal error: Cannot declare class CallbackFilterIterator, because the name is already in use

### ISSUE THREAD

**Issue by kenorb** [symfony/polyfill#108]
The project fails the PHP lint check. Here are the reproducible steps in the empty folder:

```
$ composer require symfony/polyfill-php54
...
  - Installing symfony/polyfill-php54 (v1.6.0)
...
$ find vendor -name "*.php" -exec php -l {} ';'
...
No syntax errors detected in vendor/symfony/polyfill-php54/Php54.php
Fatal error: Cannot declare class CallbackFilterIterator, because the name is already in use in vendor/symfony/polyfill-php54/Resources/stubs/CallbackFilterIterator.php on line 28
Errors parsing vendor/symfony/polyfill-php54/Resources/stubs/CallbackFilterIterator.php
```

I'm using these checks as part of the build for all Composer's libraries to verify whether the files are compatible with my PHP version, however I've got this fatal error instead.

This library was requested by [`symfony/http-foundation` v2.8.32](https://packagist.org/packages/symfony/http-foundation#v2.8.32) which was requested by `symfony/http-kernel` and [`vipsoft/code-coverage-extension`](https://github.com/vipsoft/code-coverage-extension/blob/master/composer.json) which is used for code coverage tests, so I believe v3.x is not supported yet.

**Comment by nicolas-grekas** [comment]
I'm sorry but as stated, that's not an issue with this library but with your linting process.
