### ISSUE TITLE
The polyfill should get released

### ISSUE THREAD

**Issue by stof** [symfony/polyfill#11]
This library is now used as a dependency in Twig 1.23 (and other projects are starting to use it too).
Not having a stable release means that Twig 1.23 is not installable by default in a composer project (you have to change the minimum stability or to require dev versions of ``symfony/polyfill-mbstring`` in your project to whitelist it)

**Comment by robfrawley** [comment]
+1

**Comment by stof** [comment]
@fabpot what do you think about tagging this package as stable release already ?

**Comment by keradus** [comment]
When it would be released as stable more people will know about that package... solving #1 before stable release would be great!

**Comment by stof** [comment]
@keradus there is a PR in progress already

**Comment by keradus** [comment]
yep, it was send about 15 minutes after my comment ;)

**Comment by fabpot** [comment]
1.0.0 is out now.
