### ISSUE TITLE
Polyfill for intl-idn

### ISSUE THREAD

**Issue by gharlan** [symfony/polyfill#113]
What do you think about adding a polyfill for [intl-idn](http://php.net/manual/en/ref.intl.idn.php)?

**Comment by nicolas-grekas** [comment]
why not :) do you have code?

**Comment by keradus** [comment]
why not.
perhaps https://github.com/true/php-punycode ?

**Comment by gharlan** [comment]
> do you have code?

Not yet. And I'm not sure, if I am able to do this. But maybe I will try.

> perhaps https://github.com/true/php-punycode ?

I guess we have to re-implement this to be compatible with the original functions.

Should the polyfill support the deprecated variant `INTL_IDNA_VARIANT_2003`? (I don't think so)

**Comment by nicolas-grekas** [comment]
It's OK to have a partial polyfill, so no, no need to support deprecated features (and if someone comes with a PR later, fine :) )

**Comment by gharlan** [comment]
This is the php-src part of the functions: https://github.com/php/php-src/blob/master/ext/intl/idn/idn.c
But the main conversion is done by functions `uidna_nameToASCII_UTF8` and `uidna_nameToUnicodeUTF8` from ICU.

**Comment by keradus** [comment]
> I guess we have to re-implement this to be compatible with the original functions.

well, they tried to be compatible.

we can cover it with tests, sure, see what's missing
simply, there may be no need to reimplement everything from scratch

**Comment by gharlan** [comment]
Thanks @lbassin for the pull request!
