### ISSUE TITLE
mb_convert_case with MB_CASE_TITLE: unexpected outcome on strings with underscores

### ISSUE THREAD

**Issue by decodekult** [symfony/polyfill#141]
Natively, `mb_convert_case('my_underscored_string', MB_CASE_TITLE, "UTF-8")` would return `My_Underscored_String`, but this polyfill returns `My_underscored_string` instead.

This introduces a degree of uncertainty when using this polyfill for projects on systems without the native extension.

**Comment by nicolas-grekas** [comment]
Fixed in #142
