### ISSUE TITLE
PHPCompatibility rulesets for the Symfony polyfill-php#.# packages

### ISSUE THREAD

**Issue by jrfnl** [symfony/polyfill#154]
Hi all,

This is just a "service message".

For those people who use this library and use [`PHPCompatibility`](https://github.com/PHPCompatibility/PHPCompatibility) in their CI process, there is now a set of custom rulesets available which can be used to prevent false positives being thrown by `PHPCompatibility` for the native PHP functionality being polyfilled by the various Symfony `polyfill-php#.#` packages.

You can find the repo for the Symfony polyfill rulesets here on Github as well as on Packagist.
* https://github.com/PHPCompatibility/PHPCompatibilitySymfony
* https://packagist.org/packages/phpcompatibility/phpcompatibility-symfony

Hope someone will find it useful :smile: 

P.S.: If anyone is interested in helping us maintaining the rulesets and/or adding rulesets for the other Symfony polyfill packages, please [open an issue in the repo](https://github.com/PHPCompatibility/PHPCompatibilitySymfony/issues/new).

**Comment by nicolas-grekas** [comment]
Thanks for the notice.
