### ISSUE TITLE
gzopen()  / gzopen64()

### ISSUE THREAD

**Issue by fisharebest** [symfony/polyfill#16]
On 32bit builds of Ubuntu 14.04LTS (PHP 5.5.9), three functions are created with the wrong names.
[See one of many bug reports.](https://bugs.launchpad.net/ubuntu/+source/php5/+bug/1315888)
There seems to be no plans to fix this in Ubuntu, so users of this LTS release cannot use the GZIP library.

Is there a place in this package for the necessary polyfills?

```php
if (!function_exists('gzopen') && function_exists('gzopen64')) {
	function gzopen($filename , $mode = 'r', $use_include_path = 0 ) {
		return gzopen64($filename, $mode, $use_include_path);
	}
}
if (!function_exists('gzseek') && function_exists('gzseek64')) {
	function gzseek($zp , $offset, $whence = SEEK_SET) {
		return gzseek64($zp, $offset, $whence);
	}
}
if (!function_exists('gztell') && function_exists('gztell64')) {
	function gztell($zp) {
		return gztell64($zp);
	}
}
```

**Comment by fisharebest** [comment]
> Is there a place in this package for the necessary polyfills?

PS - if the answer is "yes", then I'm happy to create a pull request...

**Comment by nicolas-grekas** [comment]
It's a yes from me, I propose adding it on the Php54 polyfill (in the bootstrap.php file, using the same CS)

**Comment by nicolas-grekas** [comment]
I meant Php56 polyfill!
