### ISSUE TITLE
Add support for JSON_THROW_ON_ERROR for the PHP 7.3 polyfill

### ISSUE THREAD

**Issue by theofidry** [symfony/polyfill#161]
If feels like it's something that could be provided by the polyfill as well. I can try to do a PR if that's ok.

Note that there is also the exception `JsonException` missing.

Also the doc for the PHP 7.3 polyfill is outdated, given the entry of the docs for the polyfills, maybe those could be automated somehow to keep them in sync.

**Comment by nicolas-grekas** [comment]
How would you implement this? Just declaring the constant maybe?

**Comment by theofidry** [comment]
If the constant is not defined then declare it yeah, or conditionally declare it based on the PHP version.

**Comment by theofidry** [comment]
damnit, indeed it's not new functions so that won't work :/ Well I'll be closing it then I guess

**Comment by theofidry** [comment]
@tm1000 it's a new function in a new namespace, it's not a polyfill for the existing native PHP function
