### ISSUE TITLE
[PHP 7.4] Add get_mangled_object_vars()

### ISSUE THREAD

**Issue by IonBazan** [symfony/polyfill#179]
There is a new function coming in PHP 7.4 called `get_mangled_object_vars()` which returns same result as `(array) $object` with the exception that it ignores overloaded array casts, such as used by ArrayObject.
Output is also similar to `get_object_vars()` but it also shows protected and private fields.

To implement that we will probably need to use `ReflectionObject`.

PHP implementation and `phpt` test:
https://github.com/php/php-src/commit/eecd8961d94c50cc6cdc94ec80df8c1ce4881a76

**Comment by nicolas-grekas** [comment]
There's also `mb_str_split()` and `password_algos()` which could be polyfilled.

For `get_mangled_vars()` I'd recommend using something like [getArrayObjectProperties](https://github.com/symfony/symfony/blob/0d8f5fe985aeed6145eaa1c32d265cb001275fbe/src/Symfony/Component/VarExporter/Internal/Exporter.php#L372) for `ArrayObject` and `ArrayIterator`, and using `(array)` for anything else, for decent performances (then we might add more exceptions as they are reported.)

PR(s) welcome :)
