### ISSUE TITLE
Incorrect implementation of hrtime

### ISSUE THREAD

**Issue by GrahamCampbell** [symfony/polyfill#186]
`hrtime` is not just a function that formats time in a certain way. It must also tick forward at a steady rate, independent of system time. Symfony's implementation relies upon `microtime`, which is at best non-strictly increasing (time sync can pause the system time to sync it, or speed it up), and at worst, may jump backwards in time if the sytem time is changed by a sysadmin, or otherwise.

All this said, it's not obvious to be how to implement this correctly. For reference, PHP's implementation is available at https://github.com/php/php-src/blob/PHP-7.3.9/ext/standard/hrtime.c.

**Comment by nicolas-grekas** [comment]
A monotonic implementation requires a using a dedicated system call. We can't do one from PHP, so there's no better implementation I'm afraid of.

**Comment by GrahamCampbell** [comment]
Right. I wonder if this shouldn't have been polyfilled, since it doesn't behave in the way it should. It would be like polyfilling the random function with something that just returned the same thing over and over. That is, in the same say doing that wouldn't have the unpredicability properties that the "random" functions have, this implementation doesn't have the monotonicity property, which is a fundamental problem I think, since this function (the native one) was created exclusively to solve that problem within PHP.

**Comment by nicolas-grekas** [comment]
We could force the implementation to be monotonic by retuning max(now, previous value)
I'll let you submit a PR if that makes sense to you.

**Comment by GrahamCampbell** [comment]
I guess that would be better, yeh. The real implementation is actually stronger than monotonic, in the sense that it doesn't pause or speed up if the clock is being synced.

**Comment by nicolas-grekas** [comment]
I know, see above :)
