### ISSUE TITLE
DateTimeInterface class constants

### ISSUE THREAD

**Issue by pawelkg** [symfony/polyfill#190]
In PHP 7.2 class constants of DateTime are now defined on DateTimeInterface. So if we call in eg. DateTimeInterface:W3C we have:
```
Fatal error:  Uncaught Error: Undefined class constant 'W3C' in ...
```

**Comment by stof** [comment]
We cannot add constants on an existing interface. That's simply impossible to polyfill in PHP.

If you need to keep compat with older versions, keep using `DateTime::W3C` to reference the constant (which also work on PHP 7.2+).
