### ISSUE TITLE
New release for symfony/polyfill-mbstring

### ISSUE THREAD

**Issue by willemstuursma** [symfony/polyfill#20]
The current release of symfony/polyfill-mbstring has an invalid composer.json scheme. This has already been fixed in the master branch, however this change has not yet been released.

This break the composer validation of dependencies for any projects that has this polyfill included:

````
symfony/polyfill-mbstring is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
The property - suggests - is not defined and the definition does not allow additional properties
````

Could you create a new release including this change.

**Comment by fabpot** [comment]
Done

**Comment by willemstuursma** [comment]
Thank you!
