### ISSUE TITLE
Intl Spoofchecker Polyfill

### ISSUE THREAD

**Issue by GrahamCampbell** [symfony/polyfill#215]
This class is not Pollyfilled by symfony, but it would be useful if it was. For example: https://github.com/egulias/EmailValidator/pull/231.

**Comment by stof** [comment]
Such polyfill could totally fit in this repo. Contributions are welcome

Given that it will probably require bundling a lot of data, I suggest implementing it as a dedicated polyfill package rather than bundling it in an existing package.

**Comment by GrahamCampbell** [comment]
This should be tagged as help wanted. I am unlikely to ever get around to implementing it, as I don't need that class myself.

**Comment by nicolas-grekas** [comment]
Closing instead, no need to keep pending issues like this.
