### ISSUE TITLE
uri_template polyfill

### ISSUE THREAD

**Issue by GrahamCampbell** [symfony/polyfill#216]
I wonder if symfony could polyfill this. Guzzle has an implementation at https://github.com/guzzle/guzzle/blob/6.5.2/src/UriTemplate.php, which is used whenever the extension is not loaded.

We are in the unique situation where the original extension now has no maintainer, so I don't know if the polyfill would end up being the only way to have the "extension" on PHP 8.

---

https://pecl.php.net/package/uri_template

**Comment by stof** [comment]
well, if the extension is unmaintained and a userland implementation becomes the only way, I might deserve being maintained as a dedicated package than as a polyfill.

**Comment by GrahamCampbell** [comment]
Maybe, yeh.

**Comment by nicolas-grekas** [comment]
Closing for the reason given by @stof
