### ISSUE TITLE
PHP 7.2 polyfill PHP_FLOAT_MAX

### ISSUE THREAD

**Issue by GrahamCampbell** [symfony/polyfill#223]
I wonder if the Symfony polyfill should fill the `PHP_FLOAT_MAX` constant.

**Comment by stof** [comment]
Well, is there a way to compute this value on older PHP versions ?

Also, if we go that way, we should probably polyfill all `PHP_FLOAT_*` constants. Polyfilling only one of them might be worse than not polyfilling them depending on how feature detection is used for these constants.
