### ISSUE TITLE
[RFC] PHP 8.0 WeakMap

### ISSUE THREAD

**Issue by michaljusiega** [symfony/polyfill#228]
There is a unstable implemention for WeakMap https://github.com/BenMorel/weakmap-polyfill added in PHP 8.0 available for >= PHP 7.4.

Maybe it would be a good idea to merge it into `symfony/polyfill-php80`?

**Comment by michaljusiega** [comment]
Nevermind :D

**Comment by stof** [comment]
Given that this weakmap polyfill requires PHP 7.4+, I don't think it belongs to this repo. We tend to polyfill for older versions. If someone needs a weakmap and is fine with requiring 7.4+, I suggest using the existing package.
