### ISSUE TITLE
Polyfill for fnmatch()

### ISSUE THREAD

**Issue by Chi-teck** [symfony/polyfill#246]
It would be useful to have a polyfill for [fnmatch](https://www.php.net/manual/en/function.fnmatch.php).

`fnmatch` is a way faster than `preg_match` but unfortunately it is not available on non-posix environments. That makes projects that aim to support a large range of environments to avoid usage of `fnmatch`.
https://www.drupal.org/project/drupal/issues/2620576

**Comment by IonBazan** [comment]
I found this implementation: https://github.com/Polycademy/upgradephp/blob/65c5a9be1e039bbc1ac83addaeba5bd875d758ea/upgrade.php#L2802 - you can try to use it as a reference.

**Comment by Ayesh** [comment]
With this much complexity, tests for this function are gonna be quite interesting.

**Comment by stof** [comment]
One thing I'm wondering is why PHP does not use its own fnmatch implementation (the one used on windows) for other non-POSIX platforms.
@nikic any idea about that ?

**Comment by stof** [comment]
The C implementation of fnmatch for Windows in the PHP code is at https://github.com/php/php-src/blob/2d1bf6970daef6a538a1f61334c81da584a6cd07/win32/fnmatch.c
This might also be an option to implement it, in case this algorithm can be faster than a regex (not sure that's the case when the algorithm is in PHP)

**Comment by nikic** [comment]
@stof Don't think there's any particular reason, most likely nobody bothered. First time I'm hearing about this function.

**Comment by nicolas-grekas** [comment]
@Chi-teck up to submit a PR to php-src and here maybe?

**Comment by Chi-teck** [comment]
@nicolas-grekas sorry, I don't have free time for this.

**Comment by nicolas-grekas** [comment]
PR welcome when anyone has time to work on this. Closing meanwhile.
