### ISSUE TITLE
Polyfill for get_resource_id()

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/polyfill#259]
As described in https://github.com/php/php-src/pull/5427

Anyone up to give it a try?

Be careful: we must also polyfill the behavior when a non-resource is passed (I don't know the behavior, it might be a warning or an exception - to be investigated).

**Comment by stof** [comment]
@nikic as you implemented the function, can you tell us what happens when passing something else than a resource ? Do we get a TypeError, a warning+`false`, something else ?

**Comment by nikic** [comment]
@stof As with all functions in PHP 8, a TypeError is thrown.
