### ISSUE TITLE
polyfill-php80 syntax error on php 7.2

### ISSUE THREAD

**Issue by kolorafa** [symfony/polyfill#264]
```
Parse error: syntax error, unexpected ':', expecting '{' in .../vendor/symfony/polyfill-php80/bootstrap.php on line 23
```

I know 7.2 is in Security Support only, but I think function definition could be written to support older php :)

**Comment by Ayesh** [comment]
hm, the error message sounds like the error PHP spits out when trying to run PHP code with return types in PHP 5.6 or older. 
Are you sure this code is run on PHP 7.2, and not a 5.* version?

**Comment by kolorafa** [comment]
It was 5.6, my bad, didn't check what version it was before switching to 7.3 wrongly assuming 7.2 :(

Thanks for that fast and helpful responses :)
