### ISSUE TITLE
Installing symfony/polyfill as well as symfony/polyfill-php80 doesn't work

### ISSUE THREAD

**Issue by GrahamCampbell** [symfony/polyfill#273]
The functions never get defined. symfony/polyfill shouldn't have claimed to replace the polyfill if it didn't?

**Comment by stof** [comment]
The bug is that the PHP8 file is missing in the `files` autoloading of the full package.

**Comment by nicolas-grekas** [comment]
See #274

**Comment by nicolas-grekas** [comment]
Wait, this is incorrect. The functions ARE defined, see the `src/bootstrap.php` file.
What made you report this issue?

**Comment by GrahamCampbell** [comment]
> What made you report this issue?

I just noticed the php80 bootstrap was missing from the composer.json. As you explained, this is not an issue though, because they are loaded by a separate bootstrap file.
