### ISSUE TITLE
[RFC] Deprecate the symfony/polyfill package on packagist

### ISSUE THREAD

**Issue by stof** [symfony/polyfill#275]
Currently, we have a (huge) symfony/polyfill registered on packagist.org for the mono-repo. The best practice since the start has always been to depend on the subtree packages (for instance, the iconv polyfill is huge). Deprecating the symfony/polyfill package on packagist.org would push for this best practice (and will simplify cases when the various polyfill packages have different root requirements).

Note that I'm *not* suggesting to abandon the mono-repo as the development source.

**Comment by stof** [comment]
@nicolas-grekas what do you think here ?

**Comment by stof** [comment]
For reference, there are 18 dependent packages registered on Packagist (including 1 abandoned packages): https://packagist.org/packages/symfony/polyfill/dependents?order_by=downloads&page=1

**Comment by nicolas-grekas** [comment]
I understand why you're suggesting this but I think that's a too hard push for best practices.
Even if we deprecate the package, we will still tag and manage the monorepo exactly as we do now.
Deprecating the package would be driven by abstract ideas that don't directly relate to technical requirements. This looks too artificial to me.

**Comment by nicolas-grekas** [comment]
Closing as explained.
