### ISSUE TITLE
[improvement] array_key_last

### ISSUE THREAD

**Issue by donaldinou** [symfony/polyfill#293]
I've note some minor performance issues on array_key_last.
A good work has been done on this pull request #150 

I think we could do a little better with array_slice instead of using both end and key function.

Here I come with [benchmarks](http://sandbox.onlinephpfunctions.com/code/5984e7ea158cbb306a9d36066967ca09e5b77ce3)

```php
function array_key_last(array $array) {
    return (!empty($array)) ? key(array_slice($array, -1, 1, true)) : null;
}
```

**Comment by jderusse** [comment]
note: the proposed version by @donaldinou has also better performance from a memory point of view:

because of Copy On Write, and because the version in #150 uses `end`, the array is duplicated in memory.
but the version of @donaldinou don't alter the original array

```php
function array_key_last2(array $array)
{
    end($array);
    return key($array);
}

$a = array_fill(0, 1024*1024, str_repeat('x', 1024*1024));
var_dump(memory_get_peak_usage(true)); // int(35655680)
array_key_last2($a);
var_dump(memory_get_peak_usage(true)); // int(69214208)
```

vs
```php
function array_key_last2(array $array)
{
    return (!empty($array)) ? key(array_slice($array, -1, 1, true)) : null;
}

$a = array_fill(0, 1024*1024, str_repeat('x', 1024*1024));
var_dump(memory_get_peak_usage(true)); // int(35655680)
array_key_last2($a);
var_dump(memory_get_peak_usage(true)); // int(35655680)
```

**Comment by nicolas-grekas** [comment]
PR welcome.
Note that there is no need to use `empty()` so that it should be:
`return $array ? key(array_slice($array, -1, 1, true)) : null;`
