### ISSUE TITLE
[RuntimeException] Could not scan for classes inside ".../vendor/symfony/polyfill-php73/Resources/stubs" which does not appear to be a file nor a folder 

### ISSUE THREAD

**Issue by H4Z** [symfony/polyfill#313]
![image](https://user-images.githubusercontent.com/44223584/98431261-b1aad400-20ee-11eb-980b-8699fe039854.png)

Help pls :(

**Comment by nicolas-grekas** [comment]
Apparently this happens since composer 2.0.5, /cc @seldaek

**Comment by nicolas-grekas** [comment]
See also https://github.com/symfony/polyfill/issues/174#issuecomment-723402482

**Comment by Seldaek** [comment]
Composer 2.0.6 is now out with a fix.

**Comment by H4Z** [comment]
> Composer 2.0.6 is now out with a fix.

Thanks work now 👍
