### ISSUE TITLE
[Uid] Polyfill conditional constants

### ISSUE THREAD

**Issue by fancyweb** [symfony/polyfill#323]
Some constants in the extension (eg: [`UUID_TYPE_MD5`](https://github.com/php/pecl-networking-uuid/blob/35718f1abfb86090f39dada8d352d95d24d72d05/uuid.c#L88)) are defined conditionally.
If the extension is loaded, the polyfill bootstrap is entirely skipped.
In the Uid component, we use some conditional constants unconditionally (eg: https://github.com/symfony/symfony/blob/c97d8502245893201f9e5cf8a363cf25f0032259/src/Symfony/Component/Uid/UuidV3.php#L25).
That can result in the weird situation where I have the extension installed, but a conditional constant is used but not defined. It crashes and it's not easy to understand why.
Shouldn't we polyfill those constants even when the extension is loaded if they don't exist?

**Comment by nicolas-grekas** [comment]
I'm not sure, because that wouldn't work for ppl that "replace" ext-uuid in their composer.json file.
We should make the Symfony Uid component behave properly when the constant doesn't exist.
Is this a situation you encountered? Does this mean the extension can fail generating v3/5 UUIDs sometimes?
The component should throw a LogicException when this happens.

**Comment by stof** [comment]
> Shouldn't we polyfill those constants even when the extension is loaded if they don't exist?

That would be worse if the constant is defined but functions (defined in the extension) don't support the corresponding feature, as you would not be able to detect such case anymore.

**Comment by fancyweb** [comment]
Yes this is a situation I am encountering. I'm going to fix it on the component then. From what I found, only Uuidv3 & Uuidv5 TYPE constants are actually impacted. Couldn't we just hardcode theirs values with a comment?

**Comment by derrabus** [comment]
@fancyweb Are you on Mac? https://bugs.php.net/80557

**Comment by fancyweb** [comment]
@derrabus No, the problem happens on a Debian 9 server.
