### ISSUE TITLE
v1.22.0 is not compatible with PHP <7.4

### ISSUE THREAD

**Issue by gmessier** [symfony/polyfill#326]
This pull request: #322 use the ??= operator that is available only since PHP 7.4.
The code should be replaced using "$encoding  = $encoding ?? mb_internal_encoding();" or the minimal version in the composer.json must be bumped to ">=7.4"

**Comment by derrabus** [comment]
Closing as explained in https://github.com/symfony/polyfill/pull/327#issuecomment-756400063
