### ISSUE TITLE
Typo in bootstrap80.php 

### ISSUE THREAD

**Issue by githoober** [symfony/polyfill#331]
See https://github.com/symfony/polyfill/commit/05bcec163ab3f5885a2109babcdd91562114c337#r46349286,

`$encoding ??= mb_internal_encoding();` is not a valid PHP construct.

**Comment by BackEndTea** [comment]
Do you mean `??=`? That was introduced in php 7.4.

The following two statements work the same.
```php
$a = $a ?? $b;
$a ??= $b;
```

**Comment by nicolas-grekas** [comment]
Duplicate of https://github.com/symfony/polyfill/issues/326, see there for more info.
