### ISSUE TITLE
PHP Error while uploading in Wordpress SVN

### ISSUE THREAD

**Issue by hellwig-data443** [symfony/polyfill#348]
I don't see this error when I use 'php -l'. I can't figure out what WordPress is looking for.

Commit failed (details follow):
Commit blocked by pre-commit hook (exit code 1) with output:

***********************************
PHP error in:
 lgpd-framework/branches/1.0.1/vendor/symfony/polyfill-intl-grapheme/bootstrap80.php:

Parse error: syntax error, unexpected '|', expecting '{' in Standard input code
 on line 25
Errors parsing Standard input code
***********************************

**Comment by stof** [comment]
There is not bug in the symfony/polyfill. The require of that file is wrapped in a PHP version check to load it only on PHP 8+. It is not meant to be required directly, and so not to be linted directly using a lower PHP version either.

**Comment by Ayesh** [comment]
FWIW, WordPress SVN server has a hook to check all incoming files with `php
-l`, and the version is PHP 7.1 at the moment. I don't think there is a way
to avoid this check, other than renaming the `.php` extension to another.

**Comment by stof** [comment]
@Ayesh but that's an issue on the wordpress SVN side if it is not compatible with such conditional imports. So that's where you should report the issue

**Comment by Ayesh** [comment]
Ah sorry yes you are right. I just wanted to save the OP from some hair
pulling. I was once baffled when it rejected some of my pushes.
