### ISSUE TITLE
Parameter types of PHPH 8.0 str_*() functions too strict

### ISSUE THREAD

**Issue by derrabus** [symfony/polyfill#365]
Our polyfills of the `str_*()` functions introduced with PHP 8.0 seem to be a bit too strict about typing. Our version throws a `TypeError` when `null` is passed to them while PHP's own implementation treats `null` like an empty string.

https://3v4l.org/0VShO

This has caused some issues on Symfony after we have migrated to the polyfilled functions, for example symfony/symfony#42290

**Comment by nicolas-grekas** [comment]
Indeed! Can you please send a PR? Don't hesitate to merge and release it once it's approved :)

**Comment by derrabus** [comment]
#366
