### ISSUE TITLE
Deliver empty polyfills when requirement is already fulfilled

### ISSUE THREAD

**Issue by cedric-anne** [symfony/polyfill#375]
I made some tests and I think there could be a solution to provide an empty polyfill package when the extension is actually loaded on the platform.

Let's say you are requiring `symfony/console` on a PHP 8.0 build having the ctype, intl and mbstring extensions loaded. Following useless polyfills will be fetched: `symfony/polyfill-ctype`, `symfony/polyfill-intl-grapheme`, `symfony/polyfill-intl-normalizer`, `symfony/polyfill-mbstring`, `symfony/polyfill-php73`, `symfony/polyfill-php80`. These are representing only a few hundreds of kilobytes, but, according to packagist stats, they are each loaded about 350k time every day. I guess a big part of these downloads aremade on platforms that have some of these extensions loaded.

Here is my proposal. It is inspired by what is done on the `paragonie/random_compat`, and assumes that https://github.com/composer/composer/issues/10167 is actually a bug.

For each polyfill, an empty `99.00.00` version is tagged. This empty version would just contain a `composer.json` file, requiring the element that is actually polyfilled, README and LICENCE, but no source code.
For instance, the `composer.json` of `symfony/polyfill-mbstring` would be patched like this:
```diff
index 2ed7a74..45c39cf 100644
--- a/composer.json
+++ b/composer.json
@@ -16,14 +16,8 @@
         }
     ],
     "require": {
-        "php": ">=7.1"
-    },
-    "autoload": {
-        "psr-4": { "Symfony\\Polyfill\\Mbstring\\": "" },
-        "files": [ "bootstrap.php" ]
-    },
-    "suggest": {
-        "ext-mbstring": "For best performance"
+        "php": ">=7.1",
+        "ext-mbstring": "*"
     },
     "minimum-stability": "dev",
     "extra": {
```

With this, we could have following different behaviours.

1) I develop a library compatible with PHP 7.x and I want to provide the PHP 8.0 polyfill, only on PHP 7.x server, as I use `fdiv` function. In this case, I could require `"symfony/polyfill-php80": "*"`.
- If my library is installed on PHP 7.x, the `1.23.1` version of `symfony/polyfill-php80` is fetched.
- If my library is installed on PHP 8.x, the `99.00.00` version of `symfony/polyfill-php80` is fetched.

2) I develop a project that everyone has to build manually on its own PHP server, using composer, and I want to provide the PHP 8.0 polyfill, only on PHP 7.x server, as I use `fdiv` function. In this case, I could require `"symfony/polyfill-php80": "*"`.
- If my project is installed on PHP 7.x, the `1.23.1` version of `symfony/polyfill-php80` is fetched.
- If my project is installed on PHP 8.x, the `99.00.00` version of `symfony/polyfill-php80` is fetched.

3) I develop a project that is distributed using a pre-built package, so I cannot know which PHP version will be used to run it, and I want to always provide the PHP 8.0 polyfill as I use `fdiv` function. In this case, I could require `"symfony/polyfill-php80": "^1.23"`.
- If my project package is built on PHP 7.x, the `1.23.1` version of `symfony/polyfill-php80` is fetched.
- If my project package is built on PHP 8.x, the `1.23.1` version of `symfony/polyfill-php80` is fetched.

**Comment by cedric-anne** [comment]
Maybe #374 could provide another solution then.

For instance, on `symfony/console`, instead of requiring `symfony/polyfill-mbstring`, the `mbstring` extension itself could be required, and maybe `symfony/polyfill-mbstring` could be added to `suggest` section.

```diff
diff --git a/composer.json b/composer.json
index 7598179c..b6f350ea 100644
--- a/composer.json
+++ b/composer.json
@@ -17,8 +17,8 @@
     ],
     "require": {
         "php": ">=7.2.5",
+        "ext-mbstring": "*",
         "symfony/deprecation-contracts": "^2.1",
-        "symfony/polyfill-mbstring": "~1.0",
         "symfony/polyfill-php73": "^1.8",
         "symfony/polyfill-php80": "^1.16",
         "symfony/service-contracts": "^1.1|^2",
@@ -39,6 +39,7 @@
     "suggest": {
         "symfony/event-dispatcher": "",
         "symfony/lock": "",
+        "symfony/polyfill-mbstring": "To provide mbstring extension polyfill",
         "symfony/process": "",
         "psr/log": "For using the console logger"
     },
```

I guess people will still fall into the trap, but maybe it would be easier to explain in the documentaition of the component that it requires the `mbstring` extension which can be provided by the `symfony/polyfill-mbstring` component.

**Comment by jderusse** [comment]
> For instance, on `symfony/console`, instead of requiring `symfony/polyfill-mbstring`, the `mbstring` extension itself could be required.

That means, people without `ext-mbstring` nor `symfony/polyfill-mbstring` will get a composer error telling that `symfony/console` can not be installed. That would be a bad DX.
