### ISSUE TITLE
`tokenizer` extension

### ISSUE THREAD

**Issue by WinterSilence** [symfony/polyfill#376]
What's about add `tokenizer` extension containing class `PhpToken`?

**Comment by keradus** [comment]
-1 for partial polyfill
if you claim that `tokenizer` extension is polyfilled, yet provide only `PhpToken` but not `token_get_all` function - PHP CS Fixer will fail to work

**Comment by WinterSilence** [comment]
@keradus it's polyfill for php less 8.0 like as intl Normalizer, `tokenizer` extension still required.

**Comment by nicolas-grekas** [comment]
> if you claim that tokenizer extension is polyfilled, yet provide only PhpToken but not token_get_all function - PHP CS Fixer will fail to work

I agree, but can't this be solved by *not* claiming that this would polyfill ext-tokenizer (since it doesn't)?

**Comment by WinterSilence** [comment]
of course, we can implement `token_get_all()` (I saw few solutions), but this is extremely expensive at maintaining

**Comment by nicolas-grekas** [comment]
We'd better *not* do this :)

**Comment by nicolas-grekas** [comment]
It could be fine to add this class to the Php80 polyfill and define the class only if `\function_exists('token_get_all')`.
Can you please send a PR @WinterSilence? (with some test cases of course)

**Comment by WinterSilence** [comment]
@nicolas-grekas send PR to current repo or [symfony/polyfill-php80](https://github.com/symfony/polyfill-php80)?

**Comment by nicolas-grekas** [comment]
To the current repo please, the other is an automatic subtree split.

**Comment by WinterSilence** [comment]
@nicolas-grekas As I'm see, package use custom legacy PhpUnit... I'm don't have time to explore this history museum and can write tests only for PhpUnit8+.

**Comment by nicolas-grekas** [comment]
That's fine, just send the PR with what you have, we'll find a way.

**Comment by WinterSilence** [comment]
@nicolas-grekas also, if `"symfony/phpunit-bridge": "^5.3|^6.0"` require same versions of phpunit, then need update `phpunit.xml.dist`: `xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/5.0/phpunit.xsd"` or `xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/6.0/phpunit.xsd"` to calm "barking" IDE (:
