### ISSUE TITLE
PHP 8.1 add UnitEnum | BackedEnum polyfill

### ISSUE THREAD

**Issue by bladl** [symfony/polyfill#379]
PHP 8.1 adds native enum support with UnitEnum and BackedEnum interfaces [https://www.php.net/manual/en/class.backedenum.php](url). I would like to send a PR with implemented interfaces. Maybe there is another workaround?

**Comment by stof** [comment]
Given that these interfaces cannot be implemented directly, I don't see any benefit about adding polyfills for them. And I see drawbacks (breaking code doing feature detection on them)
