### ISSUE TITLE
v1.24.0 unable to install on heroku with php7.4

### ISSUE THREAD

**Issue by obj63mc** [symfony/polyfill#386]
Not sure what the cause is but right now when v1.24.0 is used to install on heroku we get the following errors - 

     !     >   Problem 1
     !     >     - symfony/polyfill-ctype v1.24.0 requires php >=7.1 -> satisfiable by php[7.3.24, 7.3.25, 7.3.26, 7.3.27, 7.3.28, 7.3.29, 7.3.30, 7.3.31, 7.3.32, 7.3.33, 7.4.12, 7.4.13, 7.4.14, 7.4.15, 7.4.16, 7.4.19, 7.4.20, 7.4.21, 7.4.22, 7.4.23, 7.4.24, 7.4.25, 7.4.26, 7.4.27, 8.0.0, 8.0.0RC4, 8.0.1, 8.0.10, 8.0.11, 8.0.12, 8.0.13, 8.0.14, 8.0.2, 8.0.3, 8.0.6, 8.0.7, 8.0.8, 8.0.9, 8.1.0, 8.1.1].
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.12
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.13
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.14
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.15
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.16
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.19
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.20
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.21
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.22
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.23
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.24
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.25
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.26
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.27
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.24
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.25
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.26
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.27
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.28
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.29
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.30
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.31
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.32
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.33
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.0
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.0RC4
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.1
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.10
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.11
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.12
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.13
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.14
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.2
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.3
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.6
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.7
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.8
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.9
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.1.0
     !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.1.1
     !     >     - Installation request for symfony/polyfill-ctype v1.24.0 -> satisfiable by symfony/polyfill-ctype[v1.24.0].
     !     > 

If I revert back to v1.23.1 heroku is able to install the package correctly.  Any ideas what might be causing this?

**Comment by nicolas-grekas** [comment]
Which version of Composer do you use?
Can you try using the latest version of composer if that's not the case already?

**Comment by stof** [comment]
listing multiple PHP versions alongside versions of `symfony/polyfill-ctype` looks weird to me. At which step of the build is this happening ?

**Comment by obj63mc** [comment]
This is happening as soon as it tries to install the php dependencies/determine which version of PHP should be running.  I have tried with both composer 1 and composer 2.

Example composer.json file - 

	{
		"name": "silverstripe/installer",
		"type": "silverstripe-recipe",
		"description": "The SilverStripe Framework Installer",    
		"require": {
			"php": "~7.4.0",
			"ext-gd": "*",
			"ext-intl": "*",
			"ext-mbstring": "*",
			"ext-imagick": "*",
			"silverstripe/recipe-plugin": "^1.3",
			"silverstripe/recipe-cms": "^4.4.1@stable"
		},
		"config": {
			"process-timeout": 600,
			"allow-plugins": {
				"composer/installers": true,
				"silverstripe/vendor-plugin": true,
				"silverstripe/recipe-plugin": true
			}
		},
		"prefer-stable": true,
		"minimum-stability": "dev"
	}

Adding a hard dependency to v1.23.1 like the following installs fine.

	{
		"name": "silverstripe/installer",
		"type": "silverstripe-recipe",
		"description": "The SilverStripe Framework Installer",    
		"require": {
			"php": "~7.4.0",
			"ext-gd": "*",
			"ext-intl": "*",
			"ext-mbstring": "*",
			"ext-imagick": "*",
			"silverstripe/recipe-plugin": "^1.3",
			"silverstripe/recipe-cms": "^4.4.1@stable",
			"symfony/polyfill": "~1.23.0"
		},
		"config": {
			"process-timeout": 600,
			"allow-plugins": {
				"composer/installers": true,
				"silverstripe/vendor-plugin": true,
				"silverstripe/recipe-plugin": true
			}
		},
		"prefer-stable": true,
		"minimum-stability": "dev"
	}

Full Build Log from heroku is below - failing build log, note when it fails even when using composer 2 it states it is using composer 1 so maybe that is the issue but not something we can control - 

    -----> Building on the Heroku-20 stack
    -----> Using buildpack: heroku/php
    -----> PHP app detected
    -----> Bootstrapping...
    -----> Installing platform packages...
    !     ERROR: Failed to install system packages!
    !     
    !     Your platform requirements (for runtimes and extensions) could
    !     not be resolved to an installable set of dependencies, or a
    !     platform package repository was unreachable.
    !     
    !     This usually means that you (or packages you are using) depend
    !     on a combination of PHP versions and/or extensions that are
    !     currently not available on Heroku.
    !     
    !     The following is the full output from the installation attempt:
    !     
    !     > You are using Composer 1 which is deprecated. You should upgrade to Composer 2, see https://blog.packagist.com/deprecating-composer-1-support/
    !     > Loading repositories with available runtimes and extensions
    !     > Updating dependencies
    !     > Your requirements could not be resolved to an installable set of packages.
    !     > 
    !     >   Problem 1
    !     >     - symfony/polyfill-ctype v1.24.0 requires php >=7.1 -> satisfiable by php[7.3.24, 7.3.25, 7.3.26, 7.3.27, 7.3.28, 7.3.29, 7.3.30, 7.3.31, 7.3.32, 7.3.33, 7.4.12, 7.4.13, 7.4.14, 7.4.15, 7.4.16, 7.4.19, 7.4.20, 7.4.21, 7.4.22, 7.4.23, 7.4.24, 7.4.25, 7.4.26, 7.4.27, 8.0.0, 8.0.0RC4, 8.0.1, 8.0.10, 8.0.11, 8.0.12, 8.0.13, 8.0.14, 8.0.2, 8.0.3, 8.0.6, 8.0.7, 8.0.8, 8.0.9, 8.1.0, 8.1.1].
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.12
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.13
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.14
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.15
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.16
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.19
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.20
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.21
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.22
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.23
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.24
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.25
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.26
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.4.27
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.24
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.25
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.26
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.27
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.28
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.29
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.30
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.31
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.32
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 7.3.33
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.0
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.0RC4
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.1
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.10
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.11
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.12
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.13
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.14
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.2
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.3
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.6
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.7
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.8
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.0.9
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.1.0
    !     >     - don't install symfony/polyfill-ctype v1.24.0|don't install php 8.1.1
    !     >     - Installation request for symfony/polyfill-ctype v1.24.0 -> satisfiable by symfony/polyfill-ctype[v1.24.0].
    !     > 
    !     > Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
    !     
    !     For reference, the following runtimes are currently available:
    !     
    !     PHP:  8.1.1, 8.1.0, 8.0.14, 8.0.13, 8.0.12, 8.0.11, 8.0.10, 
    !     8.0.9, 8.0.8, 8.0.7, 8.0.6, 8.0.3, 8.0.2, 8.0.1, 8.0.0, 
    !     8.0.0RC4, 7.4.27, 7.4.26, 7.4.25, 7.4.24, 7.4.23, 7.4.22, 
    !     7.4.21, 7.4.20, 7.4.19, 7.4.16, 7.4.15, 7.4.14, 7.4.13, 
    !     7.4.12, 7.3.33, 7.3.32, 7.3.31, 7.3.30, 7.3.29, 7.3.28, 
    !     7.3.27, 7.3.26, 7.3.25, 7.3.24
    !     
    !     Please verify that all requirements for runtime versions in
    !     'composer.lock' are compatible with the list above, and ensure
    !     all required extensions are available for the desired runtimes.
    !     
    !     When choosing a PHP runtimes and extensions, please also ensure
    !     they are available on your app's stack (heroku-20), and select
    !     a different stack if needed after consulting the article below.
    !     
    !     For a list of supported runtimes & extensions on Heroku, please
    !     refer to: https://devcenter.heroku.com/articles/php-support
    !     Push rejected, failed to compile PHP app.
    !     Push failed

 Build log with the second package.json example - shows that it is composer 2, nothing changed just added in the additional dependency and composer update.

    -----> Building on the Heroku-20 stack
    -----> Using buildpack: heroku/php
    -----> PHP app detected
    -----> Bootstrapping...
    -----> Installing platform packages...
          - php (7.4.27)
          - ext-gd (bundled with php)
          - ext-intl (bundled with php)
          - ext-mbstring (bundled with php)
          - ext-imagick (3.6.0)
          - composer (2.2.3)
          - apache (2.4.51)
          - nginx (1.20.2)
    !     WARNING: Your app's PHP version is no longer actively maintained
    !     
    !     Only security updates will be provided for your PHP version
    !     series by the PHP Group until its end-of-life on 2022-11-28.
    !     
    !     It is strongly recommended you update your app to a version of
    !     PHP with "active support" status immediately to ensure you get
    !     the latest bugfixes and security updates each time you deploy.
    !     
    !     You may check the list of versions supported by the PHP Group
    !     and their EOL dates here: http://php.net/supported-versions.php
    !     
    !     For a list of supported runtimes & extensions on Heroku, please
    !     refer to: https://devcenter.heroku.com/articles/php-support
    -----> Installing dependencies...
          Composer version 2.2.3 2021-12-31 12:18:53

**Comment by stof** [comment]
As this is happening during the `Installing platform packages` step for which heroku does custom stuff with composer, you should report it to https://github.com/heroku/heroku-buildpack-php

**Comment by obj63mc** [comment]
Looks like it was actually reported - https://github.com/heroku/heroku-buildpack-php/issues/528

Will close this for now.  Thanks for your help
