### ISSUE TITLE
symfony/polyfill-php81

### ISSUE THREAD

**Issue by lxregistry** [symfony/polyfill#389]
php 8.0.15 in server, installed "symfony/polyfill-php81": "*"

receive this error

Symfony\Component\ErrorHandler\Error\UndefinedFunctionError {#1721
!!    #message: "Attempted to call function "array_is_list" from namespace "Symfony\Component\Config\Definition"."

**Comment by IonBazan** [comment]
@lxregistry Can you provide the output of `composer show`? It seems that you put the `symfony/polyfill-php81` in `replaces` section rather than `require`.
