### ISSUE TITLE
APCU polyfill register a class to be autoloadable without taking into account dependency

### ISSUE THREAD

**Issue by fgrandjean** [symfony/polyfill#39]
The \APCUIterator stubs is register to be autoloadable but it extend a class that may very well not exist.
Therfore calling :
`class_exists('\APCUIterator');` 
will trigger a Fatal Error when \APCIterator isnt available.

For exemple, \Stash\Driver\Apc::isAvailable() rely on such a call.

I think, the stubs should only be know by Composer's autoloader if it's instanciable.

**Comment by nicolas-grekas** [comment]
See #40
