### ISSUE TITLE
 Tests: invalid comparation of float values

### ISSUE THREAD

**Issue by WinterSilence** [symfony/polyfill#391]
`$this->assertEquals()` and `$this->assertSame()` generates error like as
`Failed asserting that 3.3333333333333335 is identical to 3.3333333333333.` at comparing float values.

Need replace invalid assertion to `$this->assertEqualsWithDelta()`:
`$this->assertEqualsWithDelta(3.3333333333333335, 3.3333333333333, 0.0000001)`
https://phpunit.readthedocs.io/en/7.5/assertions.html#assertequalswithdelta

**Comment by derrabus** [comment]
What exactly is the issue that you want to report?

**Comment by WinterSilence** [comment]
@derrabus failed tests

**Comment by nicolas-grekas** [comment]
This is certainly not the right repository.

**Comment by WinterSilence** [comment]
@nicolas-grekas why? this massive problem for polyfill packages

**Comment by WinterSilence** [comment]
@nicolas-grekas this failed tests on sending PR https://github.com/symfony/polyfill/runs/5335784525?check_suite_focus=true

**Comment by nicolas-grekas** [comment]
Sorry I failed to understand that your were talking about the tests of this repo. Now that I see your PR it makes sense.

**Comment by WinterSilence** [comment]
@nicolas-grekas no problem, but why issue still close?
