### ISSUE TITLE
Polyfill must be same to native class

### ISSUE THREAD

**Issue by WinterSilence** [symfony/polyfill#398]
- If native class don't have private properties and methods, then polyfill must can't have they too
- If native method don't use typing in this PHP version, then polyfill must omit typing too
- Polyfill parameters names must have names same to native method in this PHP version

i.e. polyfill `MessageFormatter`
- can't containt private properties and methods
- methods like as `MessageFormatter::formatMessage()` have untyped parameters in PHP<8
- third parameter of method `MessageFormatter::formatMessage()` have name `args` in PHP<8 and `values` in PHP>=8

as total: classes like as `MessageFormatter` must haves PHP7 and PHP8 polyfills same to native classes in this versions of PHP.

**Comment by nicolas-grekas** [comment]
No polyfill can be perfect. Eg private symbols are usually considered as an acceptable compromise. The name or arguments is of little important before PHP 8, so aligning them with PHP 8 makes sense. At least it make more sense than trying to have two classes with different names on PHP < 8 and PHP > 8, from a pragmatic perspective.

If you are affected by this, PR welcome. But if you're not affected in practice, no need to.

**Comment by WinterSilence** [comment]
@nicolas-grekas my DI container support passing arguments as assoc array i.e. named arguments in PHP<8. it can break code passes third argument as `args` instead `values`. if you pass array into `public function foo(string $str) { $this->str = $str; }`, throws error outside method's scope. if you pass array into `public  function foo($str) { $this->str = (string) $str; }` throws error inside method's scope.

**Comment by nicolas-grekas** [comment]
Understood. I'm not sure how this can be improved but if you feel like submitting a PR, I can have a look.
