### ISSUE TITLE
`enum_exists` not specified in `polyfill-php81` README 

### ISSUE THREAD

**Issue by llaville** [symfony/polyfill#400]
Even if PHP [enum-exists](https://www.php.net/manual/en/function.enum-exists) is supported by the [symfony/polyfill-php81](https://github.com/symfony/polyfill/blob/v1.25.0/src/Php81/bootstrap.php#L26-L28) it is not yet specified in README page

**Comment by nicolas-grekas** [comment]
Can you please send a PR to fix this?

**Comment by llaville** [comment]
@nicolas-grekas Done, with an extra fix ;-)
