### ISSUE TITLE
Latest change to bootstrap.php broke composer update process

### ISSUE THREAD

**Issue by hootener** [symfony/polyfill#41]
Not sure if it's me or everyone, but when running composer update with ```minimum-stability:dev``` I now receive this error:

``` 
Script php aritsan clear-compiled handling the post-update-cmd event returned with an error

[RuntimeException]
  Error Output: PHP Fatal error:  Class 'APCIterator' not found in /path/to/app/vendor/symfony/polyfill-apcu/bootstrap.php on line 32
```

I'm guessing this has something to do with [this recent commit ](https://github.com/symfony/polyfill/commit/3b7100b658ddc328a1dbeb4bbc5992c9832bc9d1)

Increasing the minimum stability bypasses the issue. However, I would like to work in dev stability, is there any workaround or fix?

**Comment by nicolas-grekas** [comment]
can you please try to replace line 32 by
`if (!class_exists('APCUIterator', false) && class_exists('APCIterator', false)) {`
does it work then?

**Comment by hootener** [comment]
That seems to have fixed it.

**Comment by webda2l** [comment]
@nicolas-grekas Temporary ````"symfony/polyfill-apcu": "@dev"```` fix the problem but a new release will be welcome to fix this error about 'APCIterator' not found
