### ISSUE TITLE
Polyfill DATE_ISO8601_EXPANDED

### ISSUE THREAD

**Issue by ro0NL** [symfony/polyfill#429]
from the phpstorm stub

```
/** @since 8.2 */
define('DATE_ISO8601_EXPANDED', "X-m-d\\TH:i:sP");
```

**Comment by stof** [comment]
@ro0NL why did you close this issue immediately after opening it ?

**Comment by ro0NL** [comment]
@stof i thought it was undoable due `X` modifier in date pattern

**Comment by stof** [comment]
if it relies on a new modifier, it is indeed not doable (polyfilling the constant without making it usable would be worse)
