### ISSUE TITLE
Missing polyfills for PHP 8.3

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/polyfill#436]
This RFC mentions new functions added to 8.3 that should be polyfilled:
https://wiki.php.net/rfc/deprecate_functions_with_overloaded_signatures

- array_keys_filter
- ldap_connect_wallet
- ldap_exop_sync
- stream_context_set_options

Help Wanted

**Comment by IonBazan** [comment]
I can look into that over the weekend 👍🏻
