### ISSUE TITLE
#[\SensitiveParameter] is available since PHP 8.2, but loaded on 8.1

### ISSUE THREAD

**Issue by leoloso** [symfony/polyfill#445]
In [`Php83/bootstrap81.php`](https://github.com/symfony/polyfill/blob/1.x/src/Php83/bootstrap81.php#L21) it's already using `#[\SensitiveParameter] string $password` in the signature of `ldap_connect_wallet`, however that's [available since PHP 8.2 only](https://www.php.net/manual/en/class.sensitiveparameter)

**Comment by derrabus** [comment]
Using undeclared classes as attributes is allowed and absolutely fine.
