### ISSUE TITLE
Backport fix for ini_parse_quantity from PHP

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/polyfill#448]
Tests are currently failing, likely related to https://github.com/php/php-src/pull/11910  and https://github.com/php/php-src/issues/11876

@fisharebest would you like to have a look and submit a fix?

**Comment by fisharebest** [comment]
Sure.  Hopefully I'll just need to remove the code I added to mimic that bug.

**Comment by nicolas-grekas** [comment]
Do you think you can tackle this soon @fisharebest? I'm wondering if I should wait for this fix before tagging the next bugfix release ;)
