### ISSUE TITLE
composer Fatal error  Call to undefined function Symfony\Polyfill\Mbstring\iconv()

### ISSUE THREAD

**Issue by dubuyifang** [symfony/polyfill#45]
phar:///usr/local/Cellar/composer/1.0.0-beta1/libexec/composer.phar/vendor/symfony/polyfill-mbstring/Mbstring.php  undefined function Symfony\Polyfill\Mbstring\iconv() when called by composer cmd on oxs 10.10.5,I had checked the phar that it had add mbstring/iconv check, How to solve this problem?
Fatal error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in phar:///usr/local/Cellar/composer/1.0.0-beta1/libexec/composer.phar/vendor/symfony/polyfill-mbstring/Mbstring.php on line 513

**Comment by nicolas-grekas** [comment]
Are you on freebsd? You need to install symfony/polyfill-iconv if you happen to not have the iconv extension installed.

**Comment by dubuyifang** [comment]
On ox s 10.10.5,How to install symfony/polyfill-iconv ?

**Comment by xabbuh** [comment]
@dubuyifang Doesn't executing `composer require symfony/polyfill-iconv` work for you?

**Comment by nicolas-grekas** [comment]
but you'd better install ext-iconv if you can!

**Comment by dubuyifang** [comment]
It had been installed ,the iconv version is iconv (GNU libiconv 1.11)
Copyright (C) 2000-2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Bruno Haible.

I had tried to call camposer require command,but it always display the same error 
$ composer require


Fatal error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in phar:///usr/local/Cellar/composer/1.0.0-beta1/libexec/composer.phar/vendor/symfony/polyfill-mbstring/Mbstring.php on line 513

**Comment by nicolas-grekas** [comment]
you need the iconv extension loaded in your php. You can check it's enabled with `php --ri iconv`, which should display `iconv support => enabled`

**Comment by dubuyifang** [comment]
I tried  php --ri iconv, but display  Extension 'iconv' not present.
I had reinstall libiconv 1.14 and executing   php --ri /usr/local/Cellar/libiconv/1.14/bin/iconv ,but display the same result.

**Comment by stof** [comment]
@dubuyifang installing libiconv on your system does not install the PHP extension, but only the system library (which is indeed a dependency of the PHP extension).
On Debian or Ubuntu, installing the extension is done with ``apt-get install php5-iconv``. I don't know about other systems.

**Comment by dubuyifang** [comment]
I called php -i  and display 
Build Date => Aug 29 2015 16:23:18
Configure Command =>  './configure'  '--without-iconv'
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /usr/local/lib


 _______________________________________________________________________


Configuration

Core

PHP Version => 5.6.10

Directive => Local Value => Master Value
allow_url_fopen => On => On
allow_url_include => Off => Off
always_populate_raw_post_data => 0 => 0
arg_separator.input => & => &
arg_separator.output => & => &
asp_tags => Off => Off
auto_append_file => no value => no value
auto_globals_jit => On => On
auto_prepend_file => no value => no value
browscap => no value => no value
default_charset => UTF-8 => UTF-8
default_mimetype => text/html => text/html
disable_classes => no value => no value
disable_functions => no value => no value
display_errors => STDOUT => STDOUT
display_startup_errors => Off => Off
doc_root => no value => no value
docref_ext => no value => no value
docref_root => no value => no value
enable_dl => On => On
enable_post_data_reading => On => On
error_append_string => no value => no value
error_log => no value => no value
error_prepend_string => no value => no value
error_reporting => no value => no value
exit_on_timeout => Off => Off
expose_php => On => On
extension_dir => /usr/local/lib/php/extensions/no-debug-non-zts-20131226 => /usr/local/lib/php/extensions/no-debug-non-zts-20131226
file_uploads => On => On
highlight.comment => <font style="color: #FF8000">#FF8000</font> => <font style="color: #FF8000">#FF8000</font>
highlight.default => <font style="color: #0000BB">#0000BB</font> => <font style="color: #0000BB">#0000BB</font>
highlight.html => <font style="color: #000000">#000000</font> => <font style="color: #000000">#000000</font>
highlight.keyword => <font style="color: #007700">#007700</font> => <font style="color: #007700">#007700</font>
highlight.string => <font style="color: #DD0000">#DD0000</font> => <font style="color: #DD0000">#DD0000</font>
html_errors => Off => Off
ignore_repeated_errors => Off => Off
ignore_repeated_source => Off => Off
ignore_user_abort => Off => Off
implicit_flush => On => On
include_path => .:/usr/local/lib/php => .:/usr/local/lib/php

Maybe something wrong in the Configuration File,But I failed to find out the correct problem.

**Comment by xabbuh** [comment]
Well, your PHP installation is built with the `--without-iconv` option which explains why the functions provided by this PHP extension are not available.

Though I think you will probably gain more feedback on how to install that extension your system on a dedicated support channel (maybe StackOverflow or some special forum for Mac users).

**Comment by Mykola-Veryha** [comment]
I have installed the 
```
composer global require symfony/polyfill-iconv
```

and I still have an error. Is there any way to use the polyfill-iconv with composer?

```
$ composer global  show -i

Fatal error: Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in phar:///usr/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php:714
Stack trace:
#0 phar:///usr/bin/composer/vendor/symfony/polyfill-mbstring/bootstrap.php(102): Symfony\Polyfill\Mbstring\Mbstring::mb_strwidth('  [Composer\\Exc...', 'ASCII')
#1 phar:///usr/bin/composer/vendor/symfony/console/Helper/Helper.php(54): mb_strwidth('  [Composer\\Exc...', 'ASCII')
#2 phar:///usr/bin/composer/vendor/symfony/console/Application.php(646): Symfony\Component\Console\Helper\Helper::strlen('  [Composer\\Exc...')
#3 phar:///usr/bin/composer/vendor/symfony/console/Application.php(127): Symfony\Component\Console\Application->renderException(Object(Composer\Exception\NoSslException), Object(Symfony\Component\Console\Output\StreamOutput))
#4 phar:///usr/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///usr/bin/composer/src/Composer/Command/GlobalCommand.php(111): Composer\Console\Application->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///usr/bin/composer/vendor/symfony/console/Application.php(835): Composer\Command\GlobalCommand->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///usr/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\GlobalCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///usr/bin/composer/src/Composer/Console/Application.php(327): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/bin/composer/src/Composer/Console/Application.php(128): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///usr/bin/composer/bin/composer(67): Composer\Console\Application->run()
#12 /usr/bin/composer(29): require('phar:///usr/bin...')
#13 {main}
  thrown in phar:///usr/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 714

```

**Comment by stof** [comment]
you mean when *running* composer ? Packages installed with `composer global` are not autoloaded while running composer (unless they are composer plugins)
