### ISSUE TITLE
Inconsistency of composer autoload and packages after removing polyfill package

### ISSUE THREAD

**Issue by vol4onok** [symfony/polyfill#465]
![Screenshot from 2024-02-28 08-57-38](https://github.com/symfony/polyfill/assets/5063777/5984ee7b-8b34-4cfb-bd65-b42d795e5ca2)

After `composer update` the current package was removed, but the composer loader try to load this package.
composer autoload didn't fix this issue.

**Comment by stof** [comment]
what was the issue ?
