### ISSUE TITLE
hex2bin() returns false if NUL bytes are in decoded string

### ISSUE THREAD

**Issue by fuhry** [symfony/polyfill#47]
hex2bin() returns false if NUL bytes are in decoded string. No error or exception is thrown which breaks code written for PHP 5.4+ that does not explicitly test for this condition, or which uses another test such as `preg_match('/^([a-f0-9]{2})*$/', $str)`.

This breaks binary-safety and is inconsistent with PHP's behavior.

**Comment by xabbuh** [comment]
Can you give a simple example that does not lead to the same result as when using the built-in function?

**Comment by fuhry** [comment]
```
fuhrymbp :: ~ » php -r 'echo hex2bin("6162006364");' | xxd
0000000: 6162 0063 64                             ab.cd
```

**Comment by binwiederhier** [comment]
No indication of a special case for \0 anywhere in PHP 5.4/5.5/7.0:
https://github.com/php/php-src/blob/PHP-5.4.45/ext/standard/string.c#L157
https://github.com/php/php-src/blob/PHP-5.5.33/ext/standard/string.c#L157
https://github.com/php/php-src/blob/PHP-7.0.5/ext/standard/string.c#L157

And @fuhry's example above shows that the PHP 5.5 version does not reject hex strings with `00` in it. As an ugly workaround, we're doing some really nasty as a post-install composer thing:

```json
    "scripts": {
        "post-autoload-dump": [
            "echo 'Replacing broken hex2bin in Symfony ...'",
            "sed -i 's/p\\\\Php54::hex2bin/\\\\Util\\\\StringUtil::hex2bin/g' vendor/symfony/polyfill-php54/bootstrap.php",
            "grep StringUtil vendor/symfony/polyfill-php54/bootstrap.php"
        ]
    }
```

Merging the pull would make our lives a lot easier :-D

**Comment by binwiederhier** [comment]
Just noticed that someone else is having the same issue: https://github.com/symfony/polyfill/issues/46
