### ISSUE TITLE
`Stringable` polyfill has no return type, breaks tests and static analysis

### ISSUE THREAD

**Issue by lkrms** [symfony/polyfill#475]
I'm not using `symfony/polyfill-php80` or any other Symfony package directly, but its [`Stringable`](https://github.com/symfony/polyfill/blob/1.x/src/Php80/Resources/stubs/Stringable.php) stub displaces my own when `--dev` dependencies are installed.

This causes tests and static analysis of `Stringable` implementations with no `__toString()` return type to succeed, which means I don't see fatal errors like `Declaration of MyClass::__toString() must be compatible with Stringable::__toString(): string` until the relevant code is in production.

PHP 8.0 introduced `Stringable::__toString()` with a return type of `string` that's enforced at runtime, so I assume it's been omitted for the benefit of PHP versions before 7.0. That being the case, I would have thought a different polyfill would be loaded on PHP 5.x and below?

Anyway, reasoning and implementation aside, hopefully we can agree that polyfill side-effects like this are undesirable 😉

**Comment by stof** [comment]
PHP 8.0 also introduces an internal mechanism that automatically adds the `string` return type to `__toString` because this magic method was already strict in earlier versions.
This is why the Stringable polyfill has been implemented without an explicit return type to allow writing code compatible with more PHP versions.

**Comment by stof** [comment]
Note that the Stringable class from the polyfill is only loaded on PHP 7.x and older. On PHP 8.0+, the native implementation is the one being used anyway.

**Comment by lkrms** [comment]
> PHP 8.0 also introduces an internal mechanism that automatically adds the `string` return type to `__toString` because this magic method was already strict in earlier versions. This is why the Stringable polyfill has been implemented without an explicit return type to allow writing code compatible with more PHP versions.

Interesting. This behaviour isn't covered in the documentation for `Stringable`, but it checks out. Yay for undocumented internal mechanisms 🎉  /s

> Note that the Stringable class from the polyfill is only loaded on PHP 7.x and older. On PHP 8.0+, the native implementation is the one being used anyway.

Yes, sorry, I should have mentioned the issue only surfaces on PHP 7.x.

**Comment by derrabus** [comment]
> PHP 8.0 introduced `Stringable::__toString()` with a return type of `string` that's enforced at runtime

No, it is not: https://3v4l.org/UpafS

> This causes tests and static analysis of `Stringable` implementations with no `__toString()` return type to succeed

Which is exactly how that interface behaves on PHP 8. Our polyfill must not be more strict than the real implementation. And even if we did, your static analysis issues would resurface once you upgrade to PHP 8.

Your static analysis issue is 100% home made.
