### ISSUE TITLE
[PHP 8.4] composer require polyfill-php84 is failing

### ISSUE THREAD

**Issue by Trismegiste** [symfony/polyfill#478]
Hello,

I must be dumb but when I type
```bash
$ composer require symfony/polyfill-php84
``` 
I get an error «_Could not find package symfony/polyfill-php84_.»

And I couldn't find the package on Packagist :thinking: 
![Capture d’écran de 2024-04-25 11-50-23](https://github.com/symfony/polyfill/assets/1260026/fb34abe2-d0f5-4020-bd6a-02c9d42f804d)

I wanted to use the new `mb_ucfirst` and I'm currently using PHP 8.3.1 in a docker environment (FrankenPHP) though I don't think it's relevant.

Thanks in advance :heart:

**Comment by derrabus** [comment]
@fabpot Can you please register the package on Packagist?

**Comment by fabpot** [comment]
Fixed now

**Comment by Trismegiste** [comment]
It works ! Thanks :rose:
