### ISSUE TITLE
mb_strlen - different behaviour for ISO-8859-1 string

### ISSUE THREAD

**Issue by ondrejmirtes** [symfony/polyfill#487]
Let's say we have this .php script that uses ISO-8859-1 encoding:

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

class LeadTransformer
{
    public const FEATURED_HOME_BANK_EXHAUSTED = 'Maisons vedettes épuisées';
}

$s = LeadTransformer::FEATURED_HOME_BANK_EXHAUSTED;
var_dump(mb_strlen($s, 'UTF-8'));
var_dump(\Symfony\Polyfill\Mbstring\Mbstring::mb_strlen($s, 'UTF-8'));
```

I'd expect this result:

```php
int(25)
int(25)
```

But instead I get:

```php
int(25)
bool(false)
```

**Comment by derrabus** [comment]
Can you investigate why that happens?

**Comment by ondrejmirtes** [comment]
So this is the polyfill implementation: https://github.com/symfony/polyfill/blob/c0fee7a4f19e41174152cb36ad95da8aaf5f5d8b/src/Mbstring/Mbstring.php#L527-L535

`$s` isn't in `UTF-8` encoding, so arguably the call gives the function wrong information, but there is still disparity in how the internal PHP function mb_strlen() behaves vs. how the polyfill behaves.

The real function returns `25` when called with `mb_strlen($s, 'UTF-8')` even if `$s` is in `ISO-8859-1`, but the polyfill returns `false`.

Here's the extension implementation: https://github.com/php/php-src/blob/0775b99d5e0e0918b38e41f346899926fb0fbbe4/ext/mbstring/mbstring.c#L1821-L1861

Looks like the mbstring extension returns some kind of sensible string length even for invalid UTF-8 strings.

So the `@iconv_strlen($s, $encoding)` isn't the right solution here, but I don't know how to implement a better one. Maybe someone fluent in C can tell what's happening in the real extension code :)

**Comment by nicolas-grekas** [comment]
The result varies by PHP versions: https://3v4l.org/ltL8k

But I also see no valid use case for passing a non-utf8 string to mb_strlen with an explicit utf-8 encoding so this is a minor issue IMHO. Better fix the code to not get into this situation...

**Comment by ondrejmirtes** [comment]
Alright, I'm fine with this, it's a very rare issue for me when PHPStan user is analysing source code that's not in UTF-8 AND does not have mbstring installed.

Thanks for your time :)
