### ISSUE TITLE
[Feature Request] Constant CURL_HTTP_VERSION_3 in PHP 8.4

### ISSUE THREAD

**Issue by ddevsr** [symfony/polyfill#488]
Can backporting new constant HTTP in 8.4?

**Comment by Ayesh** [comment]
It should be possible to polyfill this, provided the underlying Curl build has support for it.

**Comment by ddevsr** [comment]
Refering from badger https://gist.github.com/bagder/a88d3bedc8ecb69d19aeb542fa538e9b
