### ISSUE TITLE
Change "replace" to "provide" in README.md

### ISSUE THREAD

**Issue by rkrahnen** [symfony/polyfill#505]
I require multiple packages that use the "replace"-block inside the composer.json as explained in your README.md. The problem ist, that this leads to an uninstallable set of packages because for a "replace" only one package can be installed. You can find an example here: https://github.com/composer/satis/issues/930

I would suggest changing "replace" to "provide" so that multiple packages can follow your guide without leading to conflicts.

**Comment by derrabus** [comment]
The documented "replace" block is meant to be used in the root composer.json file of projects (as in: applications). Installable packages, as in libraries that can be consumed by applications or other libraries, should mention the polyfills neither in the "provides" nor the "replaces" section.

**Comment by alcohol** [comment]
I guess in our situation it is more nuanced, because generally speaking `composer/satis` is a root project (application by itself). However, some people have built extended tooling on top of it by adding it as a requirement to their project... :shrug:

**Comment by rkrahnen** [comment]
Using `replace` or `provide` to fulfill the purpose is in both cases an "abuse" of the actual idea of the two properties. However, I like the approach in principle, so that fewer packages are installed, especially if they are not needed at all.
Since both ways work for the purpose and `provide` has the advantage that there are no conflicts, I like that more.

Referring to https://github.com/symfony/polyfill/issues/505#issuecomment-2418708583: This is a wonderful example where the authors have written a package with the intention that it is a project, but the community uses it as a library to extend it. So I wouldn't blame the authors for following your idea, but it does get in the way of the community.

Since your documentation has a wide reach, I would be happy if you adapt it if I could convince you.

**Comment by stof** [comment]
both `provide` and `replace` would cause issues if you use it in a shared package, because that package does not actually provide the polyfill, which could break other packages that actually want that code.


If you want to allow Satis to be installable as a dependency without such conflict, you would have to convince the Satis to maintainers to remove that rule entirely, not to replace it with `provide`.
