### ISSUE TITLE
Normalizer::decompose() should check that reordered sequences aren't themselves reordered.

### ISSUE THREAD

**Issue by gitlost** [symfony/polyfill#56]
This can be seen using the string "\xe0\xbd\xb6\xe0\xbe\x81", which currently gets decomposed into "\xe0\xbe\xb2\xe0\xbe\x80\xe0\xbd\xb1\xe0\xbe\x80", but the reordered sequences "\xe0\xbe\x80" and "\xe0\xbd\xb1" should themselves be reordered, to give the expected NFD form "\xe0\xbe\xb2\xe0\xbd\xb1\xe0\xbe\x80\xe0\xbe\x80".

I've put in a hacky fix for this on the version of "Normalizer.php" I'm using in the "tl-normalizer" WP plugin fork, which recurses when a reordered sequence has a reordering combining class, see https://github.com/gitlost/tl-normalizer/blob/master/Symfony/Normalizer.php#L237 passim, but I'm sure there's a better way of doing it.

**Comment by nicolas-grekas** [comment]
Fixed in #61, thanks for the reports @gitlost!

**Comment by gitlost** [comment]
And thanks @nicolas-grekas for the rapid (and excellent) fixes! It's nice when a fix makes the code simpler...
