### ISSUE TITLE
iconv_substr(): Detected an illegal character in input string

### ISSUE THREAD

**Issue by gectus** [symfony/polyfill#72]
Hello

I have the same error https://github.com/symfony/polyfill/issues/63

```
[2016-08-24 15:03:51] lumen.ERROR: ErrorException: iconv_substr(): Detected an illegal character in input string in /var/www/app-storage/vendor/symfony/polyfill/src/Mbstring/Mbstring.php:417
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'iconv_substr():...', '/var/www/heaven...', 417, Array)
#1 /var/www/app-storage/vendor/symfony/polyfill/src/Mbstring/Mbstring.php(417): iconv_substr('\x01\x00\x00\x00\x00\x01\xE5', 0, 1, 'ASCII')
#2 /var/www/app-storage/vendor/symfony/polyfill/src/Mbstring/bootstrap.php(36): Symfony\Polyfill\Mbstring\Mbstring::mb_substr('\x01\x00\x00\x00\x00\x01\xE5', 0, 1, 'ASCII')
#3 /var/www/app-storage/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(163): mb_substr('\x01\x00\x00\x00\x00\x01\xE5', 0, 1, 'ASCII')
```

**Comment by nicolas-grekas** [comment]
which version of symfony/polyfill are you using?

**Comment by gectus** [comment]
```
"repositories": [
        {
            "type": "git",
            "url": "https://github.com/symfony/polyfill.git"
        }
    ],
    "require": {
        "symfony/polyfill": "dev-master"
    },
```

**Comment by stof** [comment]
please run ``composer show | grep symfony/polyfill``, which will also display the exact commit being used, because dev-master is a moving target, and so what you use depends on when you ran a composer update.

Btw, you don't need to register a git repository to use this package. It is available on Packagist.

**Comment by gectus** [comment]
`symfony/polyfill                          dev-master 2e13b98 Symfony polyfills backporting features to lower PHP versions`

**Comment by stof** [comment]
OK, this is similar to #63, but this is actually happening in another polyfilled method

**Comment by bensquire** [comment]
Same issue detected when using the previously referenced, php-amqplib/php-amqplib.

**Comment by woshiwenquan** [comment]
PHP installation `mbstring ` extension.

**Comment by bensquire** [comment]
As an interesting tidbit. I actually had php7-mbstring installed when I saw this error, installing the php-mbstring extension, fixed the problem. I use https://launchpad.net/~ondrej/+archive/ubuntu/php.
