### ISSUE TITLE
Support APCu 5.x-style increment and decrement

### ISSUE THREAD

**Issue by davidstrauss** [symfony/polyfill#73]
In APCu 4.x, attempting to increment or decrement a key that doesn't exist fails. The workaround is storing a value of `1` or `-1` to initialize the key after failing on inc/dec. I'm not sure if it would be part of the mission of this project to support things like that, but it's one of the APCu 4.x vs. 5.x challenges I deal with in LCache (in addition to the iterator).

**Comment by stof** [comment]
Well, we simply cannot redefine the function to change its behavior when using APCu 4.x. PHP does not support replacing functions which are already defined.

**Comment by davidstrauss** [comment]
I'm not really asking for a replacement, more of an abstraction that spans both behaviors if you need to support both.

**Comment by stof** [comment]
Polyfills are not about providing an abstraction. An abstraction is not a polyfill anymore but a separate API (but nothing forbids you to build such abstraction separately).

**Comment by davidstrauss** [comment]
> Polyfills are not about providing an abstraction.

I respectfully disagree. Polyfills are abstractions that just happen to provide the latest public API as the interface. Anything that hides underlying complexity or varying implementations is an abstraction.

In any case, a proper polyfill has to meet a few goals:

 1. Not implement APIs beyond those defined as the latest public APIs
 2. Provide fidelity between using the latest APIs and the polyfill
 3. Only provide its implementations where the underlying environment has gaps

You're declining to add novel functions/classes on the basis of the first and third goals, but this project currently fails to meet the second goal by having `apcu_inc` and `apcu_dec` with inconsistent behaviors. You have a quandary, as the APCu Polyfill is not a true polyfill if you don't satisfy all conditions. Since you cannot redefine functions in PHP, this project must choose which way it isn't quite a polyfill: either by adding its own, novel functions or not providing fidelity. Providing more functions is the more useful option.

Remy Sharp coined the term polyfill, and his own example of a polyfill explains its merit as not needing to feature-test or have branching behavior in code written on top of the polyfill:
> Now with the polyfiller in place, as a developer I can rely on using the Web Storage API (for sessions) and not have to feature test in my code or fork to handle different situations.

Well, right now, I have to add a condition to handle the differing behavior of APCu 4.x, even though those functions are in the scope of APCu polyfill.

**Comment by davidstrauss** [comment]
Additionally, the definition and restrictions around polyfills were originally for Javascript, a language that allows redefinition of functions and other symbols. It therefore makes sense in Javascript to draw a hard line at defining new functions in a polyfill, but the capabilities of PHP are different.

**Comment by stof** [comment]
@davidstrauss you explicitly asked to provide an abstraction, which requires creating a *new* function not part of APCu. This is out of the scope of a polyfill.
We cannot replace the **existing** function in PHP (PHP does not support monkey-patching), so it means that the behavior you are asking us cannot be polyfilled.

Creating a new API on top of APCu to support this behavior on older versions is a different topic than polyfilling (though it has some similarity with it) and it should be done by a different package that symfony/polyfill.

**Comment by nicolas-grekas** [comment]
Closing as explained by @stof: there is no way to achieve this in PHP unfortunately.
