### ISSUE TITLE
Composer can't find package symfony/polyfill-intl-icu ~1.0

### ISSUE THREAD

**Issue by JarJak** [symfony/polyfill#8]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/symfony 2.8.x-dev requires symfony/polyfill-intl-icu ~1.0 -> no matching package found.

Shouldn't it be 1.0.x-dev ?

**Comment by xabbuh** [comment]
We have `minimum-stability` set to `dev` in the `composer.json` files of the polyfill packages. If you already like to use them (or the not released Symfony 2.8) in your project, you will need to decrease the minimum stability in your project's `composer.json` file or explicitly require unstable dependencies.

**Comment by JarJak** [comment]
Ok I can wait a month until Symfony 2.8 will get stable release, thanks
