### ISSUE TITLE
[RFC] Apc polyfill

### ISSUE THREAD

**Issue by mcfedr** [symfony/polyfill#80]
I think it would be useful to have a polyfill for Apc, for the cases that `apcu_*` functions are available put `apc_*` is not.

This is the default situation when using Apcu > v5.

The polyfill would mostly be helpful in using older code that relies on `apc_*` and avoid installing the `apcu_bc` extension.

It there is agreement that this could be useful I could write it. I imagine it to be basically a complete copy of the Apcu polyfill, but with the `u` in the opposite place.

I would even be tempted to put it in the same polyfill making it simple to have code work in either situation.

**Comment by stof** [comment]
Putting it in the same polyfill does not make sense:

- loading both at the same time does not make sense (infinite loop)
- code using ``apcu_*`` functions has no reason to require a APC polyfill.

Btw, I'm rather -1 on this, for several reasons:

- our goal with polyfills is to enable writing future-proof code, not writing code based on deprecated/removed APIs
- the fact that it would trigger infinite loops when you load the polyfills for both APC and APCu without having these extensions enabled looks quite bad.

**Comment by mcfedr** [comment]
I found an existing version of this outside of symfony polyfills - https://github.com/sanis/polyfill-apc
If its not part of what Symfony whats to provide then ill use the external one.
Btw, its not going to have infinite loops because both polyfills check for the module before defining functions.

**Comment by stof** [comment]
note that their polyfill of APCIterator is broken.

Btw, it is weird that @sanis created this as a fork on the Symfony apcu polyfill, as there is no reason to share the history (they are entirely different codebases)

**Comment by sanis** [comment]
Yeah, that's really weird :) My bad. I will try to fix it in near future.

**Comment by keradus** [comment]
It's funny to fork it, but what's wierd is to basically copy-paste the code and made small adjustments, then override the copyright of file (while leaving copyright of package)...
