### ISSUE TITLE
Support ICU 58.1

### ISSUE THREAD

**Issue by bertterheide** [symfony/polyfill#81]
The current homebrew `icu4c` package is on version 58.1, while the Symfony intl polyfill package supports 57.1. This results in the following recommendation while running `./bin/symfony_requirements`: `intl ICU version installed on your system (58.1) does not match the
   ICU data bundled with Symfony (57.1)`.

Is it possible to support version 58.1 from icu4c?

**Comment by stof** [comment]
see https://github.com/symfony/symfony/pull/20564 where the work is in progress.

I'm closing this issue because the work does not happen in this repo.
