### ISSUE TITLE
IMAP extension polyfill

### ISSUE THREAD

**Issue by djmattyg007** [symfony/polyfill#83]
Is anyone aware of a polyfill for thr IMAP extension? Specifically the `imap_mime_header_decode` function, which is critical to properly decoding email headers.

**Comment by nicolas-grekas** [comment]
Can't you use mb_decode_mimeheader instead, which is polyfilled here also ?

**Comment by djmattyg007** [comment]
Wow, thank you for such a quick response!

Yes, it appears that `mb_decode_mimeheader` works perfectly as a replacement based on the test suite I'm running. Thank you immensely!

Do you think it might be worth creating a polyfill for the IMAP extension, even if it's only partial?

**Comment by nicolas-grekas** [comment]
Not convinced myself, but I'm don't use IMAP much in PHP so dunno really.

**Comment by fain182** [comment]
For anyone landing here from a search in the PHP 8.4 era (ext-imap is now unbundled to PECL): such a polyfill exists today — [fain182/ext-imap-polyfill](https://github.com/fain182/ext-imap-polyfill) (I'm the author). It covers 65 of the 75 `imap_*` functions, including `imap_mime_header_decode`, on top of webklex/php-imap, and is parity-tested against the real extension.

**Comment by djmattyg007** [comment]
@fain182 I no longer work with PHP on a regular basis, but I'm still incredibly grateful for your contribution :heart:
