### ISSUE TITLE
Replace the extensions

### ISSUE THREAD

**Issue by jasverix** [symfony/polyfill#96]
Is it possible to add all the replaced PHP extensions in "replace"? In our case it is the 'mbstring' extension. If a package requires the mbstring extension, and I am installing this package, it should work.

Ref https://github.com/composer/composer/issues/6525

**Comment by nicolas-grekas** [comment]
See #54

**Comment by jasverix** [comment]
I am sorry, pretty new to github. It was "hidden" under pull requests. Thank you, that is what i was looking for.
