### ISSUE TITLE
"Class not found" exception when using polyfill-apcu together with Zend Server

### ISSUE THREAD

**Issue by boedah** [symfony/polyfill#98]
We were happy #94 was closed and 1.5.0 released.
However, the additional file `Apcu.php` is neither in the `autoload.files` property in `composer.json` nor is it required in `bootstrap.php`.

Maybe its best to simply `require` the file in
https://github.com/symfony/polyfill/blob/master/src/Apcu/bootstrap.php#L20
so it is not loaded when Zend Server Data Cache is not enabled?

**Comment by boedah** [comment]
As a side note: even after the polyfill fix, the Symfony Configuration Checker reports a major problem:

> APC version must be at least 3.1.13 when using PHP 5.4

This is because `phpversion('apc')` does return false, as Zend Data cache only polyfills the apc_* functions....
Inception! ;)

Maybe the check for Zend Data cache should be added to https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/skeleton/app/SymfonyRequirements.php#L501 also?

**Comment by nicolas-grekas** [comment]
We were missing someone that could actually confirm #94 worked correctly.
Would you mind opening PRs with the fixes?
There is no require missing, but an entry in composer.json yes!

**Comment by boedah** [comment]
@nicolas-grekas yes, could do!

Just to make sure: you want to autoload Apcu.php for all users, regardless if they have Zend Data Cache enabled? Else we could `require` the file only when it is enabled...

**Comment by nicolas-grekas** [comment]
nope: we want the class only when required. Just adding a psr-4 entry in composer.json would do it (see other polyfills)

**Comment by stof** [comment]
@nicolas-grekas we should have a CI job testing polyfill components individually (as done for Symfony components). It would have catch such component-level autoloading mistake.

**Comment by boedah** [comment]
@stof it happens only if `extension_loaded('Zend Data Cache')`:

https://github.com/symfony/polyfill/blob/master/src/Apcu/bootstrap.php#L20

But the if-statement could be altered for the tests, I think.

**Comment by nicolas-grekas** [comment]
> But the if-statement could be altered for the tests, I think

better not if it means adding a runtime check for everyone...

**Comment by boedah** [comment]
I'm off for vacation, will do it afterwards ;)

**Comment by nicolas-grekas** [comment]
ping @boedah

**Comment by nicolas-grekas** [comment]
ping @boedah :)

**Comment by boedah** [comment]
@nicolas-grekas sorry for not responding earlier :/
However, I just did test #103 and it works fine.
